### ISSUE TITLE
Click radio buttons

### ISSUE THREAD

**Issue by SamyOteroGlez** [Behat/MinkExtension#264]
Hi,

I opened this issue before in the Behat/Behat repo and they suggested me to ask here.

In order to fill a form I need to click on a radio button but the element looks like:

```
<div class="row question-group question ">
    <label for="radio" class="question-label ">
        The field question?
    </label>
    <div class="radio">
        <input id="radio_1" name="radio" type="radio" value="1">
        <label for="radio_1">
            Yes
        </label>
        <input id="radio_2" name="radio" type="radio" value="0">
        <label for="radio_2">
            No
        </label>
    </div>
</div>
```

At this moment I cant use click() or press() functions because those are for links/buttons only .

I tried to use the function selectOption($select, $option) wish is the way to interact with radio buttons but I'm getting this error:

```
Element is not clickable at point (1245, 9.333328247070312). 
Other element would receive the click: 
<a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
```

The radio buttons are in the page but hidden. Also I searched for the element `<a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>` mentioned in the error message and its located in the navbar and the radio buttons are not even close to it.

Thanks in advance

Samy

**Comment by aik099** [comment]
What Mink driver are you using. It's not MinkBrowserKitDriver, because it can't determine if element is hidden. The MinkSelenium2Driver intentionally won't allow operating on hidden elements, but I've not see the error message you're getting before.

Probably some JS prettifies standard form controls by creating styled divs that via JS click on actual radio buttons, that same JS initially hides. If that is the case, then you should be:

* using JS-enabled driver
* clicking on styled divs (because user sees them and not radio buttons)

**Comment by SamyOteroGlez** [comment]
Thanks aik099

This is my FeatureContext class declaration. So far I'm using MinkContext

```
<?php

use Behat\Behat\Hook\Scope\BeforeFeatureScope;
use Behat\Behat\Hook\Scope\AfterFeatureScope;
use Behat\Testwork\Hook\Scope\BeforeSuiteScope;
use Behat\Testwork\Hook\Scope\AfterSuiteScope;
use Behat\Behat\Hook\Scope\BeforeScenarioScope;
use Behat\Behat\Hook\Scope\AfterScenarioScope;
use Behat\Behat\Tester\Exception\PendingException;
use Behat\Behat\Context\Context;
use Behat\MinkExtension\Context\MinkContext;
use Behat\Gherkin\Node\PyStringNode;
use Behat\Gherkin\Node\TableNode; 

//This is for DB management
use Illuminate\Database\Capsule\Manager as Capsule;
use Illuminate\Database\Eloquent\Model as Eloquent;

/**
 * Defines application features from the specific context.
 */
class FeatureContext extends MinkContext implements Context 
{
    //...
}
```

This is how looks the radio buttons:

![screenshot from 2016-12-16 09 52 45](https://cloud.githubusercontent.com/assets/8644532/21314169/7956c1de-c5c3-11e6-8797-1386e80531eb.png)

You are totally right, the radio buttons get the value after clicking on the label.

Wish JS-enabled driver should I try?

Thanks

Samy

**Comment by aik099** [comment]
Whichever best suits your needs by speed and feature set.

I would recommend Zombie (similar to Goutte, but with JavaScript support). Since it's not a real browser you can't assert element visibility.

Other options are:

* setup Selenium server and use Selenium2 driver with it
* run PhantomJS server with WebDriver emulator and use Selenium2 driver with it

Usually, though I'm not a Behat user you can specify `@javascript` tag on a particular scenario (see `@javascript` on http://docs.behat.org/en/v2.5/cookbook/behat_and_mink.html) to make that particular scenario use different (slower) driver for that particular scenario.

**Comment by SamyOteroGlez** [comment]
Thank you very much, I'll let you know about my results.

By the way, I've been following this behaviour tests libs since a couple of years and are awesome.

Great job!

Samy

**Comment by SamyOteroGlez** [comment]
The issue was that the element is at the end of the page and some how I need to be able to scroll down the page, if I do it manually during the test it will find the element.

Many thanks

Samy

**Comment by aik099** [comment]
> this behaviour tests libs

I guess you mean Mink project. THanks.

**Comment by SamyOteroGlez** [comment]
Yes, Behat/Mink.
